/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.employee.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Employee service. Represents a row in the &quot;Company_Employee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.employee.service.model.impl.EmployeeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.employee.service.model.impl.EmployeeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Employee
 * @generated
 */
@ProviderType
public interface EmployeeModel extends BaseModel<Employee> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee model instance should use the {@link Employee} interface instead.
	 */

	/**
	 * Returns the primary key of this employee.
	 *
	 * @return the primary key of this employee
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee.
	 *
	 * @param primaryKey the primary key of this employee
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the company emp ID of this employee.
	 *
	 * @return the company emp ID of this employee
	 */
	public long getCompanyEmpId();

	/**
	 * Sets the company emp ID of this employee.
	 *
	 * @param companyEmpId the company emp ID of this employee
	 */
	public void setCompanyEmpId(long companyEmpId);

	/**
	 * Returns the group ID of this employee.
	 *
	 * @return the group ID of this employee
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this employee.
	 *
	 * @param groupId the group ID of this employee
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the emp first name of this employee.
	 *
	 * @return the emp first name of this employee
	 */
	@AutoEscape
	public String getEmpFirstName();

	/**
	 * Sets the emp first name of this employee.
	 *
	 * @param empFirstName the emp first name of this employee
	 */
	public void setEmpFirstName(String empFirstName);

	/**
	 * Returns the emp last name of this employee.
	 *
	 * @return the emp last name of this employee
	 */
	@AutoEscape
	public String getEmpLastName();

	/**
	 * Sets the emp last name of this employee.
	 *
	 * @param empLastName the emp last name of this employee
	 */
	public void setEmpLastName(String empLastName);

	/**
	 * Returns the email of this employee.
	 *
	 * @return the email of this employee
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this employee.
	 *
	 * @param email the email of this employee
	 */
	public void setEmail(String email);

	/**
	 * Returns the phone of this employee.
	 *
	 * @return the phone of this employee
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this employee.
	 *
	 * @param phone the phone of this employee
	 */
	public void setPhone(String phone);

	/**
	 * Returns the company name of this employee.
	 *
	 * @return the company name of this employee
	 */
	@AutoEscape
	public String getCompanyName();

	/**
	 * Sets the company name of this employee.
	 *
	 * @param companyName the company name of this employee
	 */
	public void setCompanyName(String companyName);

	/**
	 * Returns the prof image ID of this employee.
	 *
	 * @return the prof image ID of this employee
	 */
	public long getProfImageId();

	/**
	 * Sets the prof image ID of this employee.
	 *
	 * @param profImageId the prof image ID of this employee
	 */
	public void setProfImageId(long profImageId);

	@Override
	public Employee cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}